### ISSUE TITLE
Add quote valid to date

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing-quotes#44]
https://wpinvoicing.com/support/topic/quotes-quote-valid-until/

**Comment by wpdev10** [comment]
I have added the valid until event as required. But what will happen if the valid until date is passed?

Do we need to decline the quotes or we need to set their status to expire (we will have to add new status for that)?

We will have to use the cron of WordPress for this process which will run every hour.

Kindly provide your inputs so that I can move forward.

**Comment by wpdev10** [comment]
PR merged offline while testing the whole plugin. So closing this issue.
